### ISSUE TITLE
Negative numbers breaking units

### ISSUE THREAD

**Issue by slightlytyler** [huafu/with-style-mixin#3]
First off, this is a great project. Has saved me a ton of time and headache. 

Onto my issue... Negative values seem to remove the units. Setting `margin-left: -15` with `styleBindings: ['margin-left[%]']` returns the style `margin-left: 15`.

**Comment by huafu** [comment]
K, will take care of it today or in upcoming days, thanks for reporting ;-)

**Comment by huafu** [comment]
@slightlytyler I just published `0.1.2` which is fixing this issue ;-)
